"""SKILL.md generator - produce a NANDA-compatible agent capability manifest."""
from __future__ import annotations

from typing import Any


def generate(
    *,
    name: str,
    description: str,
    skills: list[str],
    endpoint: str | None,
    agent_id: str | None = None,
) -> tuple[str, dict[str, Any]]:
    """Return (markdown, json_manifest) describing an agent as a NANDA skill."""
    skills = skills or []
    endpoint = endpoint or "https://your-agent.example.com"

    manifest: dict[str, Any] = {
        "schema": "nanda.skill/v1",
        "name": name,
        "id": agent_id,
        "description": description,
        "skills": skills,
        "endpoint": endpoint,
        "protocols": ["openai-tools", "rest"],
        "broker": {
            "registry": "AgentBroker X",
            "supports": [
                "discovery",
                "negotiation",
                "contracts",
                "escrow",
                "verification",
                "reputation",
            ],
        },
        "interface": {
            "invoke": {
                "method": "POST",
                "path": "/invoke",
                "request": {"task_spec": "object", "contract_id": "string"},
                "response": {"result": "object", "status": "string"},
            }
        },
    }

    skills_list = "\n".join(f"- `{s}`" for s in skills) or "- _none declared_"
    tools_block = "\n".join(
        f"### `{s}`\nInvoke this capability via the broker contract pipeline.\n"
        for s in skills
    )

    md = f"""# {name}

{description}

> NANDA-compatible agent skill manifest generated by **AgentBroker X**.

## Identity
- **Agent ID:** `{agent_id or "unregistered"}`
- **Endpoint:** `{endpoint}`
- **Protocols:** OpenAI tool-calling, REST

## Skills
{skills_list}

## Tools
{tools_block or "_No tools declared._"}

## Broker Integration
This agent participates in the AgentBroker X autonomous economy and supports
the full lifecycle:

1. **Discovery** - listed in the agent registry, searchable by skill.
2. **Negotiation** - accepts/counters offers via `/offers/*`.
3. **Contract** - signs autonomous contracts via `/contracts/sign`.
4. **Escrow** - work begins only after funds are locked.
5. **Verification** - outputs validated against acceptance criteria.
6. **Reputation** - outcomes update its on-network trust score.

## Invocation
```http
POST {endpoint}/invoke
Content-Type: application/json

{{
  "contract_id": "<contract-id>",
  "task_spec": {{ "...": "..." }}
}}
```
"""
    return md, manifest
